# Gopkg.toml
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true

[[override]]
  name = "github.com/tendermint/go-amino"
  source = "github.com/binance-chain/bnc-go-amino"
  version = "=v0.14.1-binance.1"

[[override]]
  name = "github.com/tendermint/iavl"
  source = "github.com/binance-chain/bnc-tendermint-iavl"
  version = "=v0.12.0-binance.0"

[[override]]
  name = "github.com/tendermint/tendermint"
  source = "github.com/binance-chain/bnc-tendermint"
  version = "=v0.30.1-binance.1"

[[constraint]]
  name = "github.com/cosmos/cosmos-sdk"
  source = "github.com/binance-chain/bnc-cosmos-sdk"
  version = "=v0.25.0-binance.8"

[[constraint]]
  name = "github.com/btcsuite/btcd"
  revision = "ed77733ec07dfc8a513741138419b8d9d3de9d2d"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/Shopify/sarama"
  version = "1.17.0"

[[constraint]]
  name = "github.com/linkedin/goavro"
  version = "2.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/deathowl/go-metrics-prometheus"

[[override]]
  name = "golang.org/x/crypto"
  source = "https://github.com/tendermint/crypto"
  revision = "3764759f34a542a3aef74d6b02e35be7ab893bba"


[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/natefinch/lumberjack"
  version = "2.1.0"