name: multi-nodes-test

on: ["push", "pull_request", "workflow_dispatch"]

jobs:
  multi-nodes-test:
    runs-on: ubuntu-latest
    env:
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: 1.16
      - uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - run: git config --global url."https://${{ secrets.GH_ACCESS_TOKEN }}@github.com".insteadOf "https://github.com"
      - run: go env -w GOPRIVATE="github.com/bnb-chain/*"
      - run: make docker.build docker.generate docker.start
      # used to debug workflow
#      - name: Setup tmate session
#        uses: mxschmitt/action-tmate@v3
      - run: sleep 10
      - run: make multi-nodes-test
