name: multi-node-test

on: ["push", "pull_request", "workflow_dispatch"]

jobs:
  multi-node-test:
    runs-on: ubuntu-latest
    env:
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: 1.16
      - uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build Docker Image
        uses: docker/build-push-action@v3
        with:
          push: false
          tags: binance/bnbdnode:latest
          context: .
          file: ./Dockerfile
          secrets: |
            github-token=${{ secrets.GH_ACCESS_TOKEN }}
          cache-from: type=gha
          cache-to: type=gha
      - run: git config --global url."https://${{ secrets.GH_ACCESS_TOKEN }}@github.com".insteadOf "https://github.com"
      - run: go env -w GOPRIVATE="github.com/bnb-chain/*"
      - run: go run ./cmd/gen_devnet
      - run: docker compose -f build/devnet/docker-compose.yml up -d
      - run: go run ./cmd/test_client
